---
- name: Déployer qBittorrent (appdata, quadlet, service)
  ansible.builtin.include_tasks: ../../quadlet_common/tasks/deploy.yml
  vars:
    quadlet_user: "{{ media_user }}"
    quadlet_name: "qbittorrent"
    quadlet_units:
      - src: qbittorrent.container.j2
        name: qbittorrent.container
        service: qbittorrent.service

- name: Ouvrir le port qBittorrent dans firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 6881/tcp
    - 6881/udp
