---
- name: Déployer Prowlarr (appdata, quadlet, service)
  ansible.builtin.include_tasks: ../../quadlet_common/tasks/deploy.yml
  vars:
    quadlet_user: "{{ media_user }}"
    quadlet_name: "prowlarr"
    quadlet_units:
      - src: prowlarr.container.j2
        name: prowlarr.container
        service: prowlarr.service
