---
- name: Déployer Sonarr (appdata, quadlet, service)
  ansible.builtin.include_tasks: ../../quadlet_common/tasks/deploy.yml
  vars:
    quadlet_user: "{{ media_user }}"
    quadlet_name: "sonarr"
    quadlet_units:
      - src: sonarr.container.j2
        name: sonarr.container
        service: sonarr.service
